server:
  port: 8080

spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/himoni?useUnicode=true&characterEncoding=utf-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: secret
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: admin
    password: 123456
    publisher-confirms: true  #支持发布确认
    virtual-host: /

  redis:
    database: 6
    host:
    port: 6379
    password: vVc++Qvodte69284TY@MNL*$9084o
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        min-idle: 8
        max-idle: 0
        timeout: 3000

  devtools:
    restart:
      enabled: true

mybatis:
  mapper-locations: classpath*:mapper/**/*Mapper.xml
  #配置了这个log-impl节点，sql无法输出到文件中，控制台可以正常打印
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

ali:
  sms:
    accessKeyId: LTAI4FrVwCKTLrTB6ix9tqsS
    accessSecret:
    signName: 大喵社区
    templateCode_CheckCode: SMS_173476438
    templateCode_FK: SMS_173476685

logging:
  config: classpath:logback.xml
  level:
    com.mycom.ssmdemo: debug  #打印sql
