server:
  port: 8081

spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/himonitest?useUnicode=true&characterEncoding=utf-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: secret

  redis:
    database: 6
    host: 47.97.100.40
    port: 6379
    password: vVc++Qvodte69284TY@MNL*$9084o
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        min-idle: 8
        max-idle: 0
        timeout: 3000

  devtools:
    restart:
      enabled: true

mybatis:
  mapper-locations: classpath*:mapper/**/*Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

ali:
  sms:
    accessKeyId: LTAI4FrVwCKTLrTB6ix9tqsS
    accessSecret: rJD7cUT97SwV9PcyiqJ5oRMV4BvzxQ
    signName: 大喵社区
    templateCode_CheckCode: SMS_173476438
    templateCode_FK: SMS_173476685

logging:
  config: classpath:logback.xml
  level:
    com.mycom.ssmdemo: debug  #打印sql
